### PR TITLE
Updating stylelint to fix font-family drama

### PR DESCRIPTION
**Pull request by ashenden**
When updated, we need to make sure to update this in CNVS and DC/OS otherwise our font-stack doesn't work as expected.

### CODE REVIEW

**Comment by ashenden** [comment]
@jfurrow how do we know when this is available on NPM and the appropriate path to update it in CNVS?

**Comment by jfurrow** [comment]
@ashenden You just do an NPM release and update the module's version in CNVS. I can walk you through that if you'd like!

**Comment by ashenden** [comment]
Can I do an NPM release for this project?  Don't I have to be added as a contributor in NPM?

**Comment by jfurrow** [comment]
@ashenden You're right; I added you as a contributor and just published the updated release, so you can update to `0.0.3` in the CNVS repo

**Comment by ashenden** [comment]
thanks!

**Pull request merged**
